### ISSUE TITLE
[Bug] Problème avec le noPunchRunning

### ISSUE THREAD

**Issue by lexinor** [SUP2Ak/supv_core#1]
Comme je l'avais dit sur ton discord il y a effectivement un soucis avec cette option.
* Quand elle est **false** rien ne pose problème, ce qui est normal
* Quand elle est **true** plusieurs problèmes surviennent : 

1. Il m'est impossible de viser pour frapper quelqu'un, le personnage se fait reset l'anim de visée constamment
2. Si je fais tout simplement un click droit pour frapper, l'animation est cancel mais en cas de spam, on peut facilement frapper quelqu'un
3. A aucun moment j'ai utilisé la touche de sprint pour tester ça

Exemple vidéo : 

https://streamable.com/jpgk30

**Comment by SUP2Ak** [comment]
Corrigé
